### ISSUE TITLE
MYRaf can't open

### ISSUE THREAD

**Issue by yucelkilic** [myrafproject/myrafproject#15]
_From [zquin...@astro.unam.mx](https://code.google.com/u/106433922789793945817/) on March 24, 2014 21:17:15_

What steps will reproduce the problem? 1. I can't open myraf
2. I press the icon but nothing happens. 3. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? I have MYRAF2.0 and my operating system is Ubuntu 12.04 Please provide any additional information below.

_Original issue: http://code.google.com/p/myrafproject/issues/detail?id=18_

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on March 25, 2014 05:27:58_

Dear Sir,

MYRAf 2.0 Beta is quite new software and we did not receive enough feedback from users and we are sorry for the problem and thank you for your report.

We tested MYRaf 2.0 Beta on Ubuntu 12.04.04 / Distro Astro 2.0 / Debian 6.0 / Fedora 18-19 etc. Maybe you have missing some dependency with Ubuntu 12.04 which are required by MYRaf 2.0 Beta. Could you provide us your "myraf2" output? For this output,

Open a terminal and give this command;

$ myraf2

Also please provide for us your IRAF version.

Best regards.

**Status:** Started  
  **Owner:** yucelkilic1  
  **Cc:** m.shemuni

**Comment by yucelkilic** [comment]
_From [zquin...@astro.unam.mx](https://code.google.com/u/106433922789793945817/) on May 06, 2014 17:39:36_

Hello

I install MYRaf2 from your repositories, i.e 'MYRaf2_on_Debian_Based' so my
version of IRAF is the provided by the download fropm the installation.

When I type $sudo myraf2 I receive this:


sudo myraf2
[sudo] password for zeus: *******
Can not load PyQT4
Traceback (most recent call last):
  File "main.py", line 34, in \<module>
    gui.logging(self, "-- %s - Did you install PyQT4?"
%(datetime.datetime.utcnow()))
NameError: name 'gui' is not defined


I check it and I have alredy install PyQT4, but I dont understand if I need
change "main.py" or what.

Thanks for your attention

Regards

Zeus Valtierra



2014-03-25 6:28 GMT-06:00 \<myrafproject@googlecode.com>:

**Comment by yucelkilic** [comment]
_From [m.shemuni](https://code.google.com/u/m.shemuni/) on May 07, 2014 01:59:15_

Dear Sir or Madam

We found the problem. There is two problems in your case.

1) You have to install PyQt4 Developer Tools. So:

Debian (Ubuntu):
$ sudo apt-get install pyqt4-dev-tools

RPM (Fedora):
$ yum install pyqt4-devel

2)There is a bug in code (We fixed it). Please download the file attached and replace it with ~/MYRaf2/main.py.

Thank you for feedback.
Good luck.

**Attachment:** [main.py](http://code.google.com/p/myrafproject/issues/detail?id=18#hc7)

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 10, 2014 15:44:44_

Dear developer m.shemuni
Thank you for distributing this program for free.
I used 1.5version.
Recently I happen to know that 2.0beta version has released.
After I installed it on my Ubuntu14.10, MYRaf2 is HOME directory not in  under Education/Science/Astronomy Menu. I tried to find Education/Science/Astronomy directory but to fail. 
When I start myraf2, the result like below

suk@suk- R430 :~$ myraf2
Can not load PyQT4
Traceback (most recent call last):
  File "main.py", line 34, in \<module>
    gui.logging(self, "-- %s - Did you install PyQT4?" %(datetime.datetime.utcnow()))
NameError: name 'gui' is not defined
suk@suk- R430 :~$ 

So, I tried to install pyqt4-dev-tool.
Please let me know which is the right one between PyQt4-4.11.1-gpl-Py2.7-Qt4.8.6-x32.exe and PyQt-x11-gpl-4.10.4.

Another problem is when I mkiraf and pyraf after installing, pyraf2.5 shows up. Does that mean not developer version is included installing process already?
How do I solve this problem. 

Additionally, I changed main.py with above attached file.

Thank you for reading.
Suk from South Korea.

**Comment by yucelkilic** [comment]
_From [m.shemuni](https://code.google.com/u/m.shemuni/) on July 11, 2014 02:52:13_

You need pyqt developer version.

and what I'm using is Python User Interface Compiler 4.10.4 for Qt version 4.8.6.

to install pyqt:
Debian (Ubuntu):
$ sudo apt-get install pyqt4-dev-tools

RPM (Fedora):
$ su
$ yum install pyqt4-devel

please download least bug fixed version of MYRaf from SVN using code below:

$ svn checkout http://myrafproject.googlecode.com/svn/trunk/ myrafproject

You will have a directory named myrafproject.

change directory to myrafproject:

$ cd myrafproject

Copy and overwrite all new files to your installation directory:

$ sudo -rfv * /usr/share/myraf

download files attached.
Copy and overwrite downloaded myraf2 to bin folder:

$ sudo cp -rfv myraf2 /bin/

make it executable:

$ sudo chmod +x /bin/myraf2

Copy and overwrite downloaded myraf2.desktop to /usr/share/applications/ folder:

$ sudo cp -rfv myraf2.desktop /usr/share/applications/

make it executable:

$ sudo chmod +x /usr/share/applications/myraf2.desktop

You must install ginga for MYRaf's new display method:

$ sudo apt-get install python-pip
$ sudo pip install ginga

All done.

**Attachment:** [myraf2 myraf2.desktop](http://code.google.com/p/myrafproject/issues/detail?id=18#hc9)

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 11, 2014 09:02:20_

Issue 21 has been merged into this issue.

**Cc:** m.shemuni

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 04:27:59_

if any case I reinstalled pyqt4-dev-tools after purge and clean, then put myraf2.
The results was like followings. It said the problem of PyQT4. Do you know why?


suk@suk- R430 :~$ sudo apt-get remove --purge pyqt4-dev-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'pyqt4-dev-tools' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
suk@suk- R430 :~$ sudo apt-get clean
suk@suk- R430 :~$ sudo apt-get install pyqt4-dev-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  pyqt4-dev-tools
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 102 kB of archives.
After this operation, 291 kB of additional disk space will be used.
Get:1 http://kr.archive.ubuntu.com/ubuntu/ saucy/main pyqt4-dev-tools i386 4.10.3-1ubuntu1 [102 kB]
Fetched 102 kB in 5s (19.2 kB/s)        
Selecting previously unselected package pyqt4-dev-tools.
(Reading database ... 257226 files and directories currently installed.)
Unpacking pyqt4-dev-tools (from .../pyqt4-dev-tools_4.10.3-1ubuntu1_i386.deb) ...
Processing triggers for man-db ...
Setting up pyqt4-dev-tools (4.10.3-1ubuntu1) ...
suk@suk- R430 :~$ myraf2
Can not load PyQT4
Traceback (most recent call last):
  File "/usr/share/myraf/main.py", line 42, in \<module>
    os.system("echo \"- " + str(datetime.datetime.utcnow()) + " - Did you install PyQT4?.\" >>$HOME/.MYRaf2/log.my")
NameError: name 'datetime' is not defined
suk@suk- R430 :~$

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 12, 2014 04:40:20_

"NameError: name 'datetime' is not defined", error fixed by r286 . Please read issue #21 for further informations.

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 13, 2014 04:38:52_

Dear yucelklllc1

I can't catch what you mean. 
Could you explain some more detail?

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 14, 2014 07:31:10_

This issue solved by re-installing python-sip package and removing python3-sip related packages from Synaptic Package Manager.

**Status:** Duplicate  
  **Mergedinto:** 21
