### ISSUE TITLE
when I click myraf2's icon, nothing happened

### ISSUE THREAD

**Issue by yucelkilic** [myrafproject/myrafproject#18]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 11, 2014 09:51:14_

Dear developer, What steps will reproduce the problem? 1. when I click myraf2's icon(Jupiter image) in the applications, nothing happened.
2. In the terminal window, it says it cannot load. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? I reboot with the ubuntu13.10 again because I failed to install pyqt-dev-tools and  launch with Ubuntu 14.10. Please provide any additional information below. when i put myraf2 in terminal window, it says "Can not load MYRaf.".
I don't know the reason of this problem. I succeeded to install all the prerequisitories, PyRAF, pyqt4-dev-tools, Astropy , Alipy and python-matplotlib. 

Sincerely, 
Suk

_Original issue: http://code.google.com/p/myrafproject/issues/detail?id=21_

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 11, 2014 09:02:19_

Dear Suk,

Thank you for taking time to report issue. Firstly please remove old MYRaf2 files/folders with giving,

$ rm -rf ~/.MYRaf2

Then, be sure you have installed all MYRaf dependencies (IRAF, PyRAF,pyqt4-dev-tools, alipy, sextractor (=>2.8.6(*))), if not, please give the following command to terminal,

$ sudo apt-get update
$ python-matplotlib python-matplotlib-data python-scipy qt4-qtconfig qtcurve oxygen-icon-theme subversion pyqt4-dev-tools python-pip 
$ sudo pip install pyraf
$ sudo pip install astropy
$ sudo pip install ginga

Then checkout MYRaf's latest developer version from subversion with,

$ svn checkout http://myrafproject.googlecode.com/svn/trunk/ myrafproject
$ sudo cp -rv myrafproject /usr/share/myraf/
$ cd /usr/share/myraf/
$ sudo cp myraf2 /usr/bin/
$ sudo chmod +x /usr/bin/myraf2
$ sudo cp myraf2.desktop /usr/share/applications/

Then,

$ myraf2

It should be work :)

Please let us know if you have more questions.

(*) You can find a debian package for Sextractor in myraf-2.0-beta-debian-based.tar.gz tar ball from Download section or as attached file.

**Status:** Duplicate  
  **Owner:** yucelkilic1  
  **Cc:** m.shemuni  
  **Labels:** Component-UI  
  **Mergedinto:** 18  


**Attachment:** [sextractor_2.8.6-2_i386.deb](http://code.google.com/p/myrafproject/issues/detail?id=21#hc1)

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 03:41:15_

Dear yucelkilic

Thank you for all your faithful response and hardships.
I did all the proceedings you recommend. And finally succeed in installing
sextractor.
Unluckily I got these results when I command myraf2 even if I checked the
pyqt3-dev-tools.

Traceback (most recent call last):
  File "/usr/share/myraf/main.py", line 42, in \<module>
    os.system("echo \"- " + str(datetime.datetime.utcnow()) + " - Did you
install PyQT4?.\" >>$HOME/.MYRaf2/log.my")
NameError: name 'datetime' is not defined
suk@suk- R430 :~$ sudo apt-get install pyqt4-dev-tools
[sudo] password for suk:
Reading package lists... Done
Building dependency tree
Reading state information... Done
pyqt4-dev-tools is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
suk@suk- R430 :~$ svn checkout http://myrafproject.googlecode.com/svn/trunk/ myrafproject

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 12, 2014 04:29:49_

Dear Suk,

Could you please just replace revision 286 's main.py file from yours?

$ cp -rv main.py /usr/share/myraf/

If this problem occurs again, remove "try and except handling" from line 27 to 45 and edit main.py like;


\# force Qt4 API v2
import sip
for cl in ('QString', 'QVariant'):
    sip.setapi(cl, 2)

import os
os.environ['QT_API'] = 'pyqt'
\# force matplotlib to use Qt4 backend
import matplotlib
matplotlib.use('Qt4Agg')

from PyQt4 import QtGui, QtCore
from PyQt4.QtGui import *
from PyQt4.QtCore import *

and save main.py file.

run command;

$ myraf2

You should get error output again and please provide us that.

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 05:15:35_

Dear developer,

I did what you recommend.
The results are the followings

suk@suk- R430 :/usr/share/myraf$ cp -rv main.py /usr/share/myraf/
cp: ‘main.py’ and ‘/usr/share/myraf/main.py’ are the same file
suk@suk- R430 :/usr/share/myraf$ myraf2
Can not load PyQT4
Traceback (most recent call last):
  File "/usr/share/myraf/main.py", line 42, in \<module>
    os.system("echo \"- " + str(datetime.datetime.utcnow()) + " - Did you install PyQT4?.\" >>$HOME/.MYRaf2/log.my")
NameError: name 'datetime' is not defined
suk@suk- R430 :/usr/share/myraf$

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 05:21:10_

I checked that replaced main.py file was edited like the same what you recommend.

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 12, 2014 06:22:11_

Dear Suk,

Please replace your /usr/share/myraf/main.py with attached main.py file with typing;

$ sudo rm -rf /usr/share/myraf/main.py
$ sudo cp -rv ~/Downloads/main.py /usr/share/myraf/

then,

$ myraf2

**Attachment:** [main.py](http://code.google.com/p/myrafproject/issues/detail?id=21#hc7)

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 13:18:36_

Dear yucelklllc
After replacing to new main.py, the results are

suk@suk- R430 :~$ sudo cp -rv ~/downloads/main.py /usr/share/myraf/
‘/home/suk/downloads/main.py’ -> ‘/usr/share/myraf/main.py’
suk@suk- R430 :~$ myraf2
Traceback (most recent call last):
  File "/usr/share/myraf/main.py", line 38, in \<module>
    from PyQt4 import QtGui, QtCore
RuntimeError: the sip module implements API v11.0 to v11.1 but the PyQt4.QtGui module requires API v10.1
suk@suk- R430 :~$

**Comment by yucelkilic** [comment]
_From [m.shemuni](https://code.google.com/u/m.shemuni/) on July 12, 2014 13:44:47_

Dear suk.
It's looks like you compiled sip manually.
Please open a terminal and write:

$ python
\>>> from PyQt4 import QtGui, QtCore

You'll get same error. So it's about you sip version. Please try to reinstall sip with:

$ sudo apt-get install --reinstall sip-dev

or totally remove it.

$ sudo apt-get remove sip-dev

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 14:04:31_

Dear m.shemuni

I reinstalled sip-dev and run myraf2, got the same results lie below.
(my previous sip v is 4.16.2 and present sip v is 4.15.2. It didn't make any difference.)


suk@suk- R430 :~$ myraf2
Traceback (most recent call last):
  File "/usr/share/myraf/main.py", line 38, in \<module>
    from PyQt4 import QtGui, QtCore
RuntimeError: the sip module implements API v11.0 to v11.1 but the PyQt4.QtGui module requires API v10.1
suk@suk- R430 :~$ sudo apt-get install --reinstall sip-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-sip-dev
Suggested packages:
  python-sip-doc
The following NEW packages will be installed:
  python-sip-dev sip-dev
0 upgraded, 2 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/166 kB of archives.
After this operation, 540 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
Selecting previously unselected package sip-dev.
(Reading database ... 259307 files and directories currently installed.)
Unpacking sip-dev (from .../sip-dev_4.15.2-1ubuntu1_i386.deb) ...
Selecting previously unselected package python-sip-dev.
Unpacking python-sip-dev (from .../python-sip-dev_4.15.2-1ubuntu1_i386.deb) ...
Processing triggers for man-db ...
Setting up sip-dev (4.15.2-1ubuntu1) ...
Setting up python-sip-dev (4.15.2-1ubuntu1) ...
suk@suk- R430 :~$ myraf2
Traceback (most recent call last):
  File "/usr/share/myraf/main.py", line 38, in \<module>
    from PyQt4 import QtGui, QtCore
RuntimeError: the sip module implements API v11.0 to v11.1 but the PyQt4.QtGui module requires API v10.1
suk@suk- R430 :~

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 14:06:19_

I reinstalled twice to check.

**Comment by yucelkilic** [comment]
_From [m.shemuni](https://code.google.com/u/m.shemuni/) on July 12, 2014 14:18:05_

Please mail me: m.shemuni@gmail.com
Let's find a solution and we'll explain step by step how fix the problem here.

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 12, 2014 14:38:54_

Dear Suk,

My sip version "is 4.14.7" and i am using Fedora 20 (MATE Compiz spin). There is a discussion about same problem, maybe you should check it.

Link: http://stackoverflow.com/questions/22589497/pyqt5-sip-api-10-level-error-api-11-required Some people solved this problem with removing some sip-related packages. Because some sip-related packages using wrong sip version.

$ sudo apt-get purge python3-sip python3-sip-dev

Hope it helps.

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 16:09:25_

I did it, but my terminal says, Package 'python3-sip-dev' is not installed, so not removed.

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 16:16:19_

suk@suk- R430 :~$ sip -V
4.15.2

**Comment by yucelkilic** [comment]
_From [sukch...@gmail.com](https://code.google.com/u/109130810236004920978/) on July 12, 2014 16:50:44_

I tried another by replacing virtualenv.py in /usr/local/lib/python2.7/dist-packages/.

def copyfile(src, dest, symlink=True):
                                 |-> change this to False


but it didn't work either.

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 14, 2014 07:28:54_

This issue solved by re-installing python-sip package and removing python3-sip related packages from Synaptic Package Manager.

**Status:** Fixed  
  **Mergedinto:**

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on July 14, 2014 07:31:10_

Issue 18 has been merged into this issue.

**Cc:** yucelkilic1
