### ISSUE TITLE
FITS display failing on MYRaf

### ISSUE THREAD

**Issue by yucelkilic** [myrafproject/myrafproject#21]
_From [m.shemuni](https://code.google.com/u/m.shemuni/) on September 24, 2014 16:43:41_

ginga is not working properly with MYRaf. ginga fits viewer working good by itself. But MYRaf can't handle displaying.

Terminal output, whenever try to click or move the mouse's cursor on display area, is like:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 252, in mouseMoveEvent
    FigureCanvasBase.motion_notify_event( self, x, y )
  File "/usr/lib64/python2.7/site-packages/matplotlib/backend_bases.py", line 1833, in motion_notify_event
    guiEvent=guiEvent)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backend_bases.py", line 1440, in __init__
    LocationEvent.__init__(self, name, canvas, x, y, guiEvent=guiEvent)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backend_bases.py", line 1358, in __init__
    xdata, ydata = trans.transform_point((x, y))
  File "/usr/lib64/python2.7/site-packages/matplotlib/transforms.py", line 1332, in transform_point
    return self.transform(np.asarray([point]))[0]
IndexError: 0-d arrays can't be indexed

This error observed on Fedora, Ubuntu and linux-Mint.

_Original issue: http://code.google.com/p/myrafproject/issues/detail?id=24_

**Comment by yucelkilic** [comment]
_From [yucelkilic1](https://code.google.com/u/yucelkilic1/) on November 05, 2014 14:45:11_

The problem fixed after upgrading matplotlib and ginga by running the following commands;

$ sudo apt-get install libfreetype6-dev libxft-dev
$ sudo pip install --upgrade matplotlib
$ sudo pip install --upgrade ginga

**Status:** Verified
